import type { ConfigContext, ExpoConfig } from 'expo/config';

type BuildProfile = 'demo' | 'development' | 'preview' | 'production';

const PROFILES: readonly BuildProfile[] = ['demo', 'development', 'preview', 'production'];

function resolveProfile(): BuildProfile {
  const raw = process.env.EXPO_PUBLIC_JUVA_ENV?.trim();
  return raw && (PROFILES as readonly string[]).includes(raw)
    ? (raw as BuildProfile)
    : 'development';
}

/**
 * Per-profile identity.
 *
 * Distinct names and bundle identifiers let a demo, preview and store build live
 * on the same device without overwriting each other's local data. Every value
 * stays overridable by environment so EAS secrets remain authoritative.
 */
const IDENTITY: Record<BuildProfile, { name: string; idSuffix: string }> = {
  demo: { name: 'Juva Demo', idSuffix: '.demo' },
  development: { name: 'Juva Dev', idSuffix: '.dev' },
  preview: { name: 'Juva Preview', idSuffix: '.preview' },
  production: { name: 'Juva', idSuffix: '' },
};

export default ({ config }: ConfigContext): ExpoConfig => {
  const profile = resolveProfile();
  const identity = IDENTITY[profile];
  const baseId = 'com.juva.mobile';

  return {
    ...config,
    name: identity.name,
    slug: 'juva',
    version: '0.2.0',
    orientation: 'portrait',
    scheme: 'juva',
    userInterfaceStyle: 'light',
    // Juva's paper tone, applied by expo-system-ui so a cold launch never
    // flashes white or black before the first frame.
    backgroundColor: '#F4F1E8',
    runtimeVersion: { policy: 'appVersion' },
    assetBundlePatterns: ['**/*'],
    // Generated by `npm run assets` from Juva's own palette; the mark is the Rail orb.
    icon: './assets/icon.png',
    ios: {
      supportsTablet: true,
      bundleIdentifier: process.env.JUVA_IOS_BUNDLE_ID ?? `${baseId}${identity.idSuffix}`,
      // Required by App Review whenever a build can reach a camera or photo library.
      infoPlist: {
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    android: {
      // Edge-to-edge is mandatory from Android 16, so there is no flag to set.
      package: process.env.JUVA_ANDROID_PACKAGE ?? `${baseId}${identity.idSuffix}`,
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#F4F1E8',
      },
    },
    web: {
      bundler: 'metro',
      output: 'single',
      favicon: './assets/favicon.png',
    },
    plugins: [
      'expo-router',
      /**
       * Required for OneSignal to work at all on iOS.
       *
       * The JS SDK alone is not enough: the plugin adds the push entitlement, the
       * background-modes key and the Notification Service Extension target that iOS needs
       * to display a remote notification. Without it OneSignal initialises and then simply
       * never receives anything — the same silent failure shape as a splash key that
       * prebuild ignores.
       *
       * `mode` selects the APNs environment. Keep it `development` until a store build:
       * a production APNs entitlement on a dev provisioning profile fails to register.
       */
      ['onesignal-expo-plugin', { mode: 'development' }],
      [
        'expo-splash-screen',
        {
          image: './assets/splash.png',
          // `contain` so the orb is never cropped on a short screen, on Juva's paper tone
          // so a cold launch does not flash white before the first frame.
          resizeMode: 'contain',
          backgroundColor: '#F4F1E8',
          imageWidth: 180,
        },
      ],
      [
        'expo-camera',
        {
          cameraPermission: 'Allow Juva to scan grocery receipts you choose to verify.',
          microphonePermission: 'Juva does not record audio.',
          recordAudioAndroid: false,
          barcodeScannerEnabled: true,
        },
      ],
      [
        'expo-secure-store',
        {
          configureAndroidBackup: true,
          faceIDPermission: 'Allow Juva to protect your account on this device.',
        },
      ],
    ],
    experiments: {
      typedRoutes: true,
    },
    extra: {
      buildProfile: profile,
      buildChannel: process.env.JUVA_BUILD_CHANNEL ?? profile,
    },
  };
};
